### PR TITLE
Use standard Goutte, fixes #328

### LINKED ISSUE #328: Switch to Goutte 3.1.1
Our change in #321 is no longer needed because https://github.com/FriendsOfPHP/Goutte/issues/232 has been fixed and tagged as 3.1.1.

### PR DESCRIPTION
**Pull request by simonwheatley**
Remove the repository definition for the HumanMade Goutte

### CODE REVIEW

**Comment by johnbillion** [comment]
You'll need to set the minimum required Goutte version to `3.1.1` too.

**Comment by simonwheatley** [comment]
@johnbillion Looks like all tests pass without that… does that make you concerned?
- https://travis-ci.org/Automattic/babble/builds/79468256
- https://travis-ci.org/Automattic/babble/builds/79467864

**Comment by simonwheatley** [comment]
My Composer log:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating guzzlehttp/guzzle dev-master (d687700 => ef728b6)
    Checking out ef728b658fe6836823aa9e7d673cb08dab216b7d

  - Updating fabpot/goutte (dev-master 8f99a86 => v3.1.1)
    Checking out 751a3dc5c4d86ec3e97c9f27133ef9694d9243cc

…snip
```

**Comment by johnbillion** [comment]
Oh no worries then. The `"fabpot/goutte": "~1.0.4|~2.0|~3.1"` dependency in mink-goutte-driver covers it. :+1:

**Pull request merged**
