### PR TITLE
Reduce dependency on Babble_Plugin class

### PR DESCRIPTION
**Pull request by johnbillion**
See #222.

Blocked by #312.

This greatly simplifies and reduces the dependency on the `Babble_Plugin` class, but doesn't remove it entirely. `Babble_Jobs`, `Babble_Languages`, `Babble_Switcher_Interface`, and `BabbleTranslationGroupTool` use its `render_admin()` and `get_option()` methods.

If I have time later today I'll revisit this and see about converting `Babble_Plugin` to a static class.

### CODE REVIEW

**Comment by simonwheatley** [comment]
Behat tests in 5.6 are failing…?

**Comment by joehoyle** [comment]
See #285 for the failing tests, it's not limited to this PR

**Comment by joehoyle** [comment]
@simonwheatley tests now passing, ready for a review/merge.

**Comment by simonwheatley** [comment]
@joehoyle @johnbillion Can you please refresh this PR, so it can be merged cleanly.

**Comment by joehoyle** [comment]
@simonwheatley done - will just need to let the build finish.

**Comment by simonwheatley** [comment]
Thanks again @joehoyle @johnbillion

**Pull request merged**
