### PR TITLE
Object cache the results of getting translation jobs

### PR DESCRIPTION
**Pull request by joehoyle**
We now grab all the jobs for an object at once regardless of status, then
filter them later. This way we get a much better cache hitrate.

Also added invalidation on deleting a job and creating jobs for a post.

See #234

### CODE REVIEW

**Comment by simonwheatley** [comment]
This looks good. Are there any tests it's appropriate to add here?

Let's wait until #271 is merged before merging this.

**Comment by joehoyle** [comment]
- [x] Add some unit tests

**Comment by simonwheatley** [comment]
@joehoyle bump

**Comment by joehoyle** [comment]
@simonwheatley @johnbillion it seems we are running tests twice right now, once for pull-requests and once for each branch, that means we have two builds on every pull-request. On other projects, I've typically turned off the "test every branch" option in Travis, so we only have to have the single PR build. 

Other than that - this PR should be good to go, added tests!

**Comment by simonwheatley** [comment]
@joehoyle @johnbillion Can you please refresh the branch so it will merge cleanly, please?

**Comment by joehoyle** [comment]
@simonwheatley done! just waiting for the build.

**Comment by joehoyle** [comment]
Doh, I guess there was some pretty big changes merged in. I'll take a look at this tomorrow.

**Comment by simonwheatley** [comment]
@joehoyle Thanks! :smiley:

**Comment by joehoyle** [comment]
@simonwheatley phew, got there! I think the merge from `develop` didn't bring the `add_action` changes with it. Passing now.

**Pull request merged**
