### PR TITLE
Fix behat tests

### PR DESCRIPTION
**Pull request by joehoyle**
Run the webserver on port 80

### CODE REVIEW

**Comment by johnbillion** [comment]
There's [a cURL error on Travis](https://travis-ci.org/Automattic/babble/jobs/76184024) for the login step :(

> cURL error 7: couldn't connect to host (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\ConnectException)

I wonder if switching to `127.0.0.1` would work.

**Comment by johnbillion** [comment]
Hm that didn't work. cURL can't connect to `localhost`/`127.0.0.1`. It might be because Travis uses ipv6 and [doesn't expose an ipv4 address](http://docs.travis-ci.com/user/ci-environment/#Networking) for its boxes.

**Comment by simonwheatley** [comment]
> Does this affect the Travis environment? See 781d1a3

@johnbillion @joehoyle Yes, defining `sudo: true` bars us from the Travis container infrastructure and forces us to use VM based test instances… not the end of the world, but slower. Talk me through what we gain from it (because if it's "working tests" then that's a strong argument :smiley:).

> Hm that didn't work. cURL can't connect to localhost/127.0.0.1. It might be because Travis uses ipv6 and doesn't expose an ipv4 address for its boxes.

@johnbillion I get a similar error locally, do you?

**Comment by joehoyle** [comment]
Closed in favour of #321

**Pull request closed without merging**
