### PR TITLE
Builds on 331 to add tests

### PR DESCRIPTION
**Pull request by simonwheatley**
Includes @richaber's fixes from #331, and includes some search tests and additional infrastructure to support these tests.
- [x] Fix fatals in tests (see #333)
- [x] Add basic tests for search
- [x] Add tests for search in the context of a static front page

### CODE REVIEW

**Comment by simonwheatley** [comment]
Looks like tests are failing for multisite, e.g. https://travis-ci.org/Automattic/babble/jobs/80895773 :grimacing:

**Comment by simonwheatley** [comment]
> Looks like tests are failing for multisite, e.g. https://travis-ci.org/Automattic/babble/jobs/80895773 :grimacing:

Tests do pass when I manually run the series of actions in a real multisite, so something is affecting them in the PHPUnit environment.

**Comment by simonwheatley** [comment]
Restarting a Travis job due to a sudden database failure in mid-Behat testing… seems like this happens a fair amount currently. :unamused:

**Comment by david-binda** [comment]
Merged, thank you @richaber

**Pull request merged**
